name = "whats-up-crm-manager"
compatibility_date = "2023-05-18"
assets = { directory = "./dist" }

# Configurações para Cloudflare Pages
[env.production]
VITE_SUPABASE_URL = "https://katsiwvrfolsnkwwnnkx.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdHNpd3ZyZm9sc25rd3dubmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDQyMzQsImV4cCI6MjA2NTQyMDIzNH0.blmo4dk4c7JrXjmPLHPk_bzV6ad_eeFiyCvr4lw4CAc"
VITE_APP_NAME = "CRM WhatsApp Manager"
VITE_APP_VERSION = "1.0.0"
VITE_DEV_MODE = "false"
VITE_DEBUG_MODE = "false"

[env.preview]
VITE_SUPABASE_URL = "https://katsiwvrfolsnkwwnnkx.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdHNpd3ZyZm9sc25rd3dubmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDQyMzQsImV4cCI6MjA2NTQyMDIzNH0.blmo4dk4c7JrXjmPLHPk_bzV6ad_eeFiyCvr4lw4CAc"
VITE_APP_NAME = "CRM WhatsApp Manager"
VITE_APP_VERSION = "1.0.0"
VITE_DEV_MODE = "false"
VITE_DEBUG_MODE = "true"
